#!/usr/bin/with-contenv bash
# Script to prepare for a clean distribution.
#
rm -f predict predict.h
rm -f clients/samples/demo
rm -f utils/moontracker/moontracker
rm -f utils/geosat/geosat
cd clients
	rm -f map/map
	cd gsat-1.1.0
		make clean
		cd ..
	rm -f earthtrack/earthtrack
	rm -f kep_reload/kep_reload
	cd ..
cp -p $NOAA_HOME/.predict/predict.tle default/predict.tle
cp -p $NOAA_HOME/.predict/predict.db default/predict.db
echo "Done!"
