version: '3.8'
services:
  raspi-noaa2:
    image: ghcr.io/kx1t/raspberry-noaa-v2
    container_name: noaa
    hostname: noaa
    restart: always
    environment:
      - VERBOSELOG=true
      - latitude=42.40487
      - longitude=-71.16615
      - altitude=18
      - timezone_offset=4
      - test_gain=7.7
      - test_sdr_device_id=0
      - test_enable_bias_tee=false
      - test_freq_offset=0
      - meteor_receiver='rtl_fm'
      - noaa_receiver='rtl_fm'
      - noaa_15_schedule=true
      - noaa_15_sdr_device_id=0
      - noaa_15_freq_offset=0
      - noaa_15_enable_bias_tee=false
      - noaa_15_gain=0
      - noaa_15_sun_min_elevation=6
      - noaa_15_sat_min_elevation=30
      - noaa_18_schedule=true
      - noaa_18_sdr_device_id=0
      - noaa_18_freq_offset=0
      - noaa_18_enable_bias_tee=false
      - noaa_18_gain=0
      - noaa_18_sun_min_elevation=6
      - noaa_18_sat_min_elevation=30
      - noaa_19_schedule=true
      - noaa_19_sdr_device_id=0
      - noaa_19_freq_offset=0
      - noaa_19_enable_bias_tee=false
      - noaa_19_gain=0
      - noaa_19_sun_min_elevation=6
      - noaa_19_sat_min_elevation=30
      - meteor_m2_schedule=true
      - meteor_m2_sdr_device_id=0
      - meteor_m2_freq_offset=0
      - meteor_m2_enable_bias_tee=false
      - meteor_m2_gain=0
      - meteor_m2_sun_min_elevation=6
      - meteor_m2_sat_min_elevation=30
      - meteor_m2_memory_threshold=600
      - days_to_schedule_passes=3
      - delete_audio=false
      - flip_meteor_image=true
      - produce_spectrogram=true
      - noaa_crop_telemetry=false
      - image_annotation_location='NorthWest'
      - extend_for_annotation=false
      - produce_noaa_pristine_image=false
      - produce_noaa_pristine_histogram=false
      - produce_polar_az_el_graph=false
      - produce_polar_direction_graph=true
      - ground_station_location=''
      - show_sun_elevation=true
      - show_pass_direction=true
      - noaa_daytime_enhancements='MCIR MCIR-precip MSA MSA-precip HVC-precip HVCT-precip HVC HVCT ZA therm CC HE HF MD BD MB JF JJ LC TA WV NO sea'
      - noaa_nighttime_enhancements='MCIR MCIR-precip HVCT ZA therm NO TA sea'
      - noaa_crop_toptobottom=true
      - noaa_interpolate=false
      - noaa_map_crosshair_enable=false
      - noaa_map_crosshair_color="0xffff00"
      - noaa_map_grid_degrees=10.0
      - noaa_map_grid_color="0xff0000"
      - noaa_map_country_border_enable=true
      - noaa_map_country_border_color="0xffff00"
      - noaa_map_state_border_enable=true
      - noaa_map_state_border_color="0xffff00"
      - noaa_thermal_temp_overlay=false
      - noaa_thermal_temp_overlay_location='NorthEast'
      - timezone=America/New_York
      - lang_setting=en
      - web_server_name=raspberry-noaa.localdomain
      - enable_non_tls=true
      - web_port=80
      - enable_tls=false
      - web_tls_port=443
      - cert_valid_days=365
      - lock_admin_page=false
      - admin_username='admin'
      - admin_password='admin'
      - web_passes_date_format='m/d/Y'
      - web_datetime_format='m/d/Y H:i:s'
      - log_level=DEBUG
      - enable_satvis=true
      - enable_animation=false
      - delete_oldest_n=0
      - delete_older_than_n=0
      - disable_at_mail=false
      - enable_email_push=false
      - email_push_address=test@ifttt.com
      - enable_email_schedule_push=false
      - enable_discord_push=false
      - discord_webhook_url=''
      - enable_twitter_push=false
      - enable_slack_push=false
      - slack_push_url=''
      - slack_push_to=''
      - slack_link='https://XXXX/captures/listImages'
      - enable_matrix_push=false
    ports:
      - 89:80
      - 8073:8073   # for audio testing
    devices:
      - /dev/bus/usb
    tmpfs:
      - /tmp
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
      - /opt/noaa/srv:/srv
