#!/usr/bin/with-contenv bash
#shellcheck shell=bash

APPNAME="$(hostname)/nginx"

echo "[$(date)][$APPNAME] Started as an s6 service"
echo "[$(date)][$APPNAME] Starting the NGINX service..."

while true
do
    touch /tmp/nginx.up
    /usr/sbin/nginx -g 'daemon off;'
    rm -f /tmp/nginx.up
    echo "[$(date)][$APPNAME] NGINX Service has exited."
    sleep 10
    echo "[$(date)][$APPNAME] Restarting NGINX Service now..."
done
