#!/usr/bin/with-contenv bash
#shellcheck shell=bash

# Run cron daemon
# (C) 2022 by kx1t (Ramon F. Kolb), license: GPLv3.

set -euo pipefail

APPNAME="$(hostname)/cron"
echo "[$(date)][$APPNAME] Starting cron daemon ..."

while true
do
	/usr/sbin/cron

	# this is necessary to ensure that cron reloads any previously created crontabs:
	find /var/spool/cron/crontabs -exec touch {} +
	find /etc -name "cron*" -exec touch {} +
	while pgrep -x cron >/dev/null 2>&1
	do
		# really, do nothing, just check again in a few seconds
		# I didn't choose "10" seconds because I don't want it to overlap with the ATD daemon
		# which checks every 10 seconds. Just spreading out the (minimal) load...
		sleep 13
	done
	echo "[$(date)][$APPNAME] Cron daemon has excited. Restarting..."
done
