#!/usr/bin/with-contenv bash
#shellcheck shell=bash

APPNAME="$(hostname)/schedule"

echo "[$(date)][$APPNAME] Waiting for ATD to be active ..."

while ! pgrep atd >/dev/null 2>&1
do
    sleep 1
done

echo "[$(date)][$APPNAME] ATD is up. Now downloading the schedule ..."

cd /RaspiNOAA2/scripts
./schedule.sh -t -x \
 | stdbuf -o0 sed --unbuffered '/^$/d' | stdbuf -o0 awk '{print "[" strftime("%a %b %e %T %Z %Y", systime()) "]['"$APPNAME"'] " $0}'

echo "[$(date)][$APPNAME] Schedule downloaded."

sleep infinity
