#!/usr/bin/with-contenv bash
#shellcheck shell=bash

set -euo pipefail
set -a				# export all variables!

APPNAME="$(hostname)/scheduler"
echo "[$(date)][$APPNAME] Started as an s6 service"

NOAA_HOME="/RaspiNOAA2"
source "$NOAA_HOME/.noaa-v2.conf"
source "$NOAA_HOME/scripts/common.sh"

# fix some params so we can assume they exist:
[[ -z "$PRUNE_OLDER_THAN" ]] && PRUNE_OLDER_THAN="0"
[[ -z "$PRUNE_OLDEST" ]] && PRUNE_OLDEST="0"

# sleep until upcoming midnight:
sleep "$(( $(date -d 0:00 +%s) + 86400 - $(date +%s) ))"

# no do this every 24 hours:
while true
do
	/RaspiNOAA2/scripts/schedule.sh -t
	(( PRUNE_OLDER_THAN > 0 )) && "$NOAA_HOME/scripts/prune_scripts/prune_older_than.sh"
	(( PRUNE_OLDEST > 0 )) && "$NOAA_HOME/scripts/prune_scripts/prune_oldest.sh"

	# Go back to sleep for 24 hours...
	sleep 86400 # sleep for 24 hours
done
