#!/usr/bin/with-contenv bash
#shellcheck shell=bash

set -euo pipefail

APPNAME="$(hostname)/atd"

logfile="/var/log/raspberry-noaa-v2/output.log"

echo "[$(date)][$APPNAME] Starting AT daemon ..."
/usr/sbin/atd -f -l 10 -d 2>&1 \
    | stdbuf -o0 sed --unbuffered '/^$/d' | stdbuf -o0 awk '{print "[" strftime("%a %b %e %T %Z %Y", systime()) "]['"$APPNAME"'] " $0}'
echo "[$(date)][$APPNAME] AT daemon exited. Restarting ..."
sleep 1
