#!/bin/bash
#
# Invoke as kepupdate -q in crontab scripts to keep the update "quiet".
#
 
dir=$HOME/.predict

wget -qr www.celestrak.com/NORAD/elements/amateur.txt -O $dir/amateur.txt
wget -qr www.celestrak.com/NORAD/elements/visual.txt -O $dir/visual.txt
wget -qr www.celestrak.com/NORAD/elements/weather.txt -O $dir/weather.txt

cat $dir/amateur.txt $dir/visual.txt $dir/weather.txt > $dir/keps.tle

if [ -e $dir/keps.tle ]; then
	predict -u $dir/keps.tle

	if [[ $1 != "-q" ]] && [[ $1 != "-quiet" ]] && [[ $1 != "--quiet" ]]; then
		echo "PREDICT's Keps have been updated!"
	fi
fi

# Copy the update if there's a DOS version of PREDICT under DOSEMU

if [ -e $HOME/.dosemu/drive_c/predict/predict.tle ]; then
	todos < $dir/predict.tle > $HOME/.dosemu/drive_c/predict/predict.tle
fi

rm $dir/amateur.txt $dir/visual.txt $dir/weather.txt

