#!/usr/bin/with-contenv bash
#shellcheck shell=bash

set -euo pipefail

waitexternal() {
        while kill -0 "$1" &> /dev/null; do
                sleep 0.1
        done
}

for pidfile in /var/run/php-fpm/*.pid; do
        # if there's no pid files, we might not expand the glob
        if ! [[ -f "$pidfile" ]]; then
                continue
        fi
        pid="$(cat "$pidfile")"
        kill "$pid"
        waitexternal "$pid"
done
