---
- name: noaa environment variables
  template:
    src: noaa-v2.conf.j2
    dest: /RaspiNOAA2/.noaa-v2.conf
    owner: root
    group: root
    mode: 0644

- name: predict directory
  file:
    path: /RaspiNOAA2/.predict
    state: directory
    owner: root
    group: root
    mode: 0755

- name: predict config file
  template:
    src: predict.qth.j2
    dest: /RaspiNOAA2/.predict/predict.qth
    owner: root
    group: root
    mode: 0644

- name: wxtoimg config file
  template:
    src: wxtoimgrc.j2
    dest: /RaspiNOAA2/.wxtoimgrc
    owner: root
    group: root
    mode: 0644

- name: wxtoimg license terms acceptance file
  copy:
    src: wxtoimglic
    dest: /RaspiNOAA2/.wxtoimglic
    owner: root
    group: root
    mode: 0644

- name: log directory for raspberry-noaa-v2 logs
  become: yes
  file:
    path: /var/log/raspberry-noaa-v2
    state: directory
    owner: root
    group: root
    mode: 0755

- name: logrotate settings for raspberry-noaa-v2 logs
  become: yes
  copy:
    src: logrotate-settings
    dest: /etc/logrotate.d/raspberry-noaa-v2
    owner: root
    group: root
    mode: 0644

- name: gnuradio home directory
  file:
    path: /RaspiNOAA2/.gnuradio
    state: directory
    owner: root
    group: root
    mode: 0755

- name: gnuradio prefs directory
  file:
    path: /RaspiNOAA2/.gnuradio/prefs
    state: directory
    owner: root
    group: root
    mode: 0755

- name: gnuradio prefs file
  copy:
    src: vmcircbuf_default_factory
    dest: /RaspiNOAA2/.gnuradio/prefs/vmcircbuf_default_factory
    owner: root
    group: root
    mode: 0644

# - name: disable wifi power mgmt script
#   become: yes
#   copy:
#     src: disable-wifi-powermgmt.sh
#     dest: /usr/local/sbin/disable-wifi-powermgmt.sh
#     owner: root
#     group: root
#     mode: 0755
#   when: disable_wifi_power_mgmt | bool
#   register: wifi_powermgmt_script

# - name: disable wifi power mgmt service definition
#   become: yes
#   copy:
#     src: disable-wifi-powermgmt.service
#     dest: /lib/systemd/system/disable-wifi-powermgmt.service
#     owner: root
#     group: root
#     mode: 0644
#   when: disable_wifi_power_mgmt | bool
#   register: wifi_powermgmt_service

#- name: enable systemd wifi power management disable service
#  become: yes
#  systemd:
#    daemon_reload: yes
#    name: disable-wifi-powermgmt.service
#    enabled: yes
 # when: (wifi_powermgmt_script.changed or wifi_powermgmt_service.changed) and (disable_wifi_power_mgmt|bool)

- name: annotation directory
  file:
    path: /RaspiNOAA2/config/annotation
    state: directory
    owner: root
    group: root
    mode: 0755

- name: annotation file (sample for modification)
  copy:
    src: annotation.html.j2_file
    dest: /RaspiNOAA2/config/annotation/annotation.html.j2
    force: no
    owner: root
    group: root
    mode: 0600

- name: annotation file image (sample for modification)
  copy:
    src: raspberry-noaa-v2-logo.png
    dest: /RaspiNOAA2/config/annotation/raspberry-noaa-v2-logo.png
    force: no
    owner: root
    group: root
    mode: 0600
...
