---
- name: install raspberry-noaa-v2 core
  hosts: core
  connection: local
  gather_facts: no
  pre_tasks:
    - name: get os release
      shell: 'sed -n ''s/VERSION_CODENAME=\(.*\)/\1/p'' <(cat /etc/os-release)'
      register: raspbian_version
      check_mode: no
      changed_when: no
  roles:
    - role: common
...
