---
# available languages for webpanel (see "Lang" directory files)
available_langs: [ ar, de, en, es, sr ]

# root git clone directory (where functionality exists)
noaa_home: "/RaspiNOAA2"

# database file
db_file: "{{ noaa_home }}/db/panel.db"

# website content directory
web_home: "/var/www/wx-new"

# output root directories for images, audio, and video
output_root: /srv
output_root_rel: srv
images_output: "{{ output_root }}/images"
audio_output: "{{ output_root }}/audio"
videos_output: "{{ output_root }}/videos"

images_output_rel: "{{ output_root_rel }}/images"
audio_output_rel: "{{ output_root_rel }}/audio"
videos_output_rel: "{{ output_root_rel }}/videos"

# file used for NOAA animations
noaa_animation_output: "{{ videos_output }}/RollingAnimation.mp4"
noaa_animation_output_rel: "{{ videos_output_rel }}/RollingAnimation.mp4"

# ramfs location
ramfs_path: "/run"

# log output file
log_file: "/var/log/raspberry-noaa-v2/output.log"

# TLS self-signed certs
tls_cert: /etc/ssl/certs/local_server.crt
tls_cert_key: /etc/ssl/private/local_server.key
...
